version: '3.8'

services:
  erp-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-frontend-dev
    ports:
      - "30001:3000"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Exclude node_modules to use container's version
      - /app/node_modules
      # Mount cache directories for better performance
      - node_modules_cache:/app/node_modules
      - next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable polling for file changes in containers
      - NEXT_TELEMETRY_DISABLED=1
    # Enable hot reloading
    stdin_open: true
    tty: true
    # Restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules_cache:
  next_cache: